[package]
name = "dll"
version = "0.1.0"
edition = "2021"
crate-type = ['cdylib']

[lib]
name = "mc_export"
crate-type = ['cdylib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
